export class vehicleHelpers {

    static getVehicleByCode(code) {
        const vehicles = this.fetchVehicles();
        if (typeof code != "undefined") {
            vehicles.forEach( vehicle => {
                if (vehicle.code.toLowerCase() === code.toLowerCase()) {
                    return vehicle;
                }
            })
        }
    }

    static fetchVehicles() {
        const vehicles = [
            {
                "tl": "1",
                "name": "Double Canoe, 30'",
                "code": "doubleCanoe",
                "hp": "60",
                "st": "0",
                "hnd": "1",
                "sr": "3",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1.5",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL1 (Sailboat)",
                "loadedWeight": "3.2",
                "load": "1.5",
                "emptyWeight": "1.7",
                "sm": "5",
                "crew": "6",
                "passengers": "6",
                "dr": "2",
                "range": "-1",
                "cost": "14000",
                "locations": "EMOS",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "Large Hide Boat, 36'",
                "code": "largeHideBoat",
                "hp": "25",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "1",
                "skill": "Boating/TL1 (Sailboat)",
                "loadedWeight": "3.34",
                "load": "3.22",
                "emptyWeight": "0.12",
                "sm": "6",
                "crew": "2",
                "passengers": "1",
                "dr": "2",
                "range": "-1",
                "cost": "1000",
                "locations": "MO",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "2",
                "name": "Square-Rigged Sailboat, 37.5'",
                "code": "squareRiggedSailboat",
                "hp": "61",
                "st": "0",
                "hnd": "-1",
                "sr": "2",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "1",
                "skill": "Boating/TL2 (Sailboat)",
                "loadedWeight": "7",
                "load": "5.25",
                "emptyWeight": "1.75",
                "sm": "6",
                "crew": "3",
                "passengers": "0",
                "dr": "1",
                "range": "-1",
                "cost": "15000",
                "locations": "MO",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Sewn-Plank Sailboat, 22'",
                "code": "sewnPlankSailboat",
                "hp": "40",
                "st": "0",
                "hnd": "1",
                "sr": "2",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1.5",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL3 (Sailboat)",
                "loadedWeight": "2.2",
                "load": "1.7",
                "emptyWeight": "0.5",
                "sm": "4",
                "crew": "4",
                "passengers": "0",
                "dr": "1",
                "range": "-1",
                "cost": "1400",
                "locations": "MO",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Badan, 30'",
                "code": "badan",
                "hp": "73",
                "st": "0",
                "hnd": "-1",
                "sr": "2",
                "ht": "10",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1",
                "moveDownwind": "3",
                "acceleration": "0.2",
                "skill": "Boating/TL3 (Sailboat)",
                "loadedWeight": "15",
                "load": "12",
                "emptyWeight": "3",
                "sm": "5",
                "crew": "9",
                "passengers": "0",
                "dr": "2",
                "range": "-1",
                "cost": "5600",
                "locations": "M",
                "draft": "6",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Boum, 60'",
                "code": "boum",
                "hp": "137",
                "st": "0",
                "hnd": "-2",
                "sr": "3",
                "ht": "10",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1",
                "moveDownwind": "4",
                "acceleration": "0.15",
                "skill": "Boating/TL3 (Sailboat)",
                "loadedWeight": "80",
                "load": "60",
                "emptyWeight": "20",
                "sm": "7",
                "crew": "12",
                "passengers": "0",
                "dr": "2",
                "range": "-1",
                "cost": "37000",
                "locations": "2M",
                "draft": "10",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Cog, 60'",
                "code": "cog",
                "hp": "147",
                "st": "0",
                "hnd": "-3",
                "sr": "4",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "0.1",
                "skill": "Boating/TL3 (Sailboat)",
                "loadedWeight": "85",
                "load": "60",
                "emptyWeight": "25",
                "sm": "7",
                "crew": "18",
                "passengers": "0",
                "dr": "5",
                "range": "-1",
                "cost": "140000",
                "locations": "M",
                "draft": "13",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Hulk, 60'",
                "code": "hulk",
                "hp": "157",
                "st": "0",
                "hnd": "-4",
                "sr": "5",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "0.05",
                "skill": "Boating/TL3 (Sailboat)",
                "loadedWeight": "105",
                "load": "75",
                "emptyWeight": "30",
                "sm": "7",
                "crew": "18",
                "passengers": "0",
                "dr": "5",
                "range": "-1",
                "cost": "170000",
                "locations": "M",
                "draft": "11",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Baghlah, 120'",
                "code": "baghlah",
                "hp": "208",
                "st": "0",
                "hnd": "-4",
                "sr": "4",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "6",
                "acceleration": "0.1",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "350",
                "load": "280",
                "emptyWeight": "70",
                "sm": "9",
                "crew": "15",
                "passengers": "0",
                "dr": "2",
                "range": "-1",
                "cost": "130000",
                "locations": "2MS",
                "draft": "15",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Fishing Junk, 33'",
                "code": "fishingJunk",
                "hp": "77",
                "st": "0",
                "hnd": "-1",
                "sr": "3",
                "ht": "13",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1.5",
                "moveDownwind": "3",
                "acceleration": "0.15",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "12",
                "load": "8.5",
                "emptyWeight": "3.5",
                "sm": "5",
                "crew": "6",
                "passengers": "0",
                "dr": "3",
                "range": "-1",
                "cost": "33000",
                "locations": "2M",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Pole Junk, 140'",
                "code": "poleJunk",
                "hp": "252",
                "st": "0",
                "hnd": "-5",
                "sr": "6",
                "ht": "13",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2.5",
                "moveDownwind": "5",
                "acceleration": "0.05",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "300",
                "load": "175",
                "emptyWeight": "125",
                "sm": "9",
                "crew": "25",
                "passengers": "0",
                "dr": "5",
                "range": "-1",
                "cost": "1200000",
                "locations": "3MS",
                "draft": "10",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Trade Junk, 70'",
                "code": "tradeJunk",
                "hp": "96",
                "st": "0",
                "hnd": "-3",
                "sr": "4",
                "ht": "13",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "0.1",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "23",
                "load": "16",
                "emptyWeight": "7",
                "sm": "7",
                "crew": "12",
                "passengers": "0",
                "dr": "4",
                "range": "-1",
                "cost": "65000",
                "locations": "3M",
                "draft": "4",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Brig, 50'",
                "code": "brig",
                "hp": "131",
                "st": "0",
                "hnd": "-2",
                "sr": "3",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "4",
                "acceleration": "0.25",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "70",
                "load": "52.5",
                "emptyWeight": "17.5",
                "sm": "7",
                "crew": "15",
                "passengers": "10",
                "dr": "3",
                "range": "-1",
                "cost": "165000",
                "locations": "2M",
                "draft": "5",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Sloop, 21'",
                "code": "sloop",
                "hp": "43",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1.5",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL4 (Sailboat)",
                "loadedWeight": "2.4",
                "load": "1.8",
                "emptyWeight": "0.6",
                "sm": "4",
                "crew": "3",
                "passengers": "3",
                "dr": "2",
                "range": "-1",
                "cost": "5000",
                "locations": "M",
                "draft": "3",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Dugout Canoe, 8'",
                "code": "dugoutCanoe",
                "hp": "24",
                "st": "0",
                "hnd": "1",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "2",
                "acceleration": "1",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "0.26",
                "load": "0.15",
                "emptyWeight": "0.11",
                "sm": "1",
                "crew": "1",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "920",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Kayak, 18'",
                "code": "kayak",
                "hp": "14",
                "st": "0",
                "hnd": "2",
                "sr": "1",
                "ht": "12",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "2",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "0.12",
                "load": "0.1",
                "emptyWeight": "0.02",
                "sm": "3",
                "crew": "1",
                "passengers": "0",
                "dr": "1",
                "range": "FP",
                "cost": "500",
                "locations": "E",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Large Bark Canoe, 20'",
                "code": "largeBarkCanoe",
                "hp": "22",
                "st": "0",
                "hnd": "1",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1.25",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "0.88",
                "load": "0.8",
                "emptyWeight": "0.08",
                "sm": "3",
                "crew": "4",
                "passengers": "0",
                "dr": "1",
                "range": "FP",
                "cost": "220",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Long Dugout Canoe, 30'",
                "code": "longDugoutCanoe",
                "hp": "40",
                "st": "0",
                "hnd": "0",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "2.75",
                "load": "2.25",
                "emptyWeight": "0.5",
                "sm": "4",
                "crew": "12",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "4000",
                "locations": "O",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Oblong Hide Boat, 5'",
                "code": "oblongHideBoat",
                "hp": "16",
                "st": "0",
                "hnd": "0",
                "sr": "1",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "2",
                "moveDownwind": "2",
                "acceleration": "1",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "0.18",
                "load": "0.15",
                "emptyWeight": "0.03",
                "sm": "1",
                "crew": "1",
                "passengers": "0",
                "dr": "1",
                "range": "FP",
                "cost": "85",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Outrigger Canoe, 30'",
                "code": "outriggerCanoe",
                "hp": "45",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "2.95",
                "load": "2.25",
                "emptyWeight": "0.7",
                "sm": "5",
                "crew": "12",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "6000",
                "locations": "OR",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Round Hide Boat, 5'",
                "code": "roundHideBoat",
                "hp": "23",
                "st": "0",
                "hnd": "-1",
                "sr": "2",
                "ht": "10",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1",
                "moveDownwind": "1",
                "acceleration": "0.4",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "1.3",
                "load": "1.2",
                "emptyWeight": "0.1",
                "sm": "2",
                "crew": "2",
                "passengers": "0",
                "dr": "1",
                "range": "FP",
                "cost": "280",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "War Canoe, 60'",
                "code": "warCanoe",
                "hp": "66",
                "st": "0",
                "hnd": "-2",
                "sr": "2",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "4",
                "moveDownwind": "4",
                "acceleration": "1.25",
                "skill": "Boating/TL0 (Unpowered)",
                "loadedWeight": "5.8",
                "load": "3.6",
                "emptyWeight": "2.2",
                "sm": "6",
                "crew": "30",
                "passengers": "1",
                "dr": "3",
                "range": "FP",
                "cost": "18000",
                "locations": "O",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "Fowling Boat, 16'",
                "code": "fowlingBoat",
                "hp": "29",
                "st": "0",
                "hnd": "0",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1",
                "moveDownwind": "1",
                "acceleration": "1",
                "skill": "Boating/TL1 (Unpowered)",
                "loadedWeight": "0.52",
                "load": "0.32",
                "emptyWeight": "0.2",
                "sm": "2",
                "crew": "2",
                "passengers": "1",
                "dr": "0",
                "range": "FP",
                "cost": "560",
                "locations": "3E",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "Large Hide Boat, 36'",
                "code": "largeHideBoat",
                "hp": "25",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "4",
                "moveDownwind": "4",
                "acceleration": "2",
                "skill": "Boating/TL1 (Unpowered)",
                "loadedWeight": "3.34",
                "load": "3.22",
                "emptyWeight": "0.12",
                "sm": "6",
                "crew": "10",
                "passengers": "1",
                "dr": "2",
                "range": "FP",
                "cost": "1000",
                "locations": "O",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "River Barge, 40'",
                "code": "riverBarge",
                "hp": "56",
                "st": "0",
                "hnd": "-2",
                "sr": "3",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "1",
                "moveDownwind": "1",
                "acceleration": "0.5",
                "skill": "Boating/TL1 (Unpowered)",
                "loadedWeight": "4.2",
                "load": "2.8",
                "emptyWeight": "1.4",
                "sm": "6",
                "crew": "9",
                "passengers": "0",
                "dr": "3",
                "range": "FP",
                "cost": "12000",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "Sampan, 15'",
                "code": "sampan",
                "hp": "22",
                "st": "0",
                "hnd": "1",
                "sr": "2",
                "ht": "13",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1.5",
                "skill": "Boating/TL1 (Unpowered)",
                "loadedWeight": "0.28",
                "load": "0.2",
                "emptyWeight": "0.08",
                "sm": "3",
                "crew": "1",
                "passengers": "1",
                "dr": "2",
                "range": "FP",
                "cost": "1800",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "1",
                "name": "Sewn-Plank Riverboat, 30'",
                "code": "sewnRiverboat",
                "hp": "40",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1.25",
                "skill": "Boating/TL1 (Unpowered)",
                "loadedWeight": "2",
                "load": "1.5",
                "emptyWeight": "0.5",
                "sm": "4",
                "crew": "10",
                "passengers": "2",
                "dr": "2",
                "range": "FP",
                "cost": "1400",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "2",
                "name": "Fishing Boat, 27'",
                "code": "fishingBoat",
                "hp": "43",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "0.6",
                "skill": "Boating/TL2 (Unpowered)",
                "loadedWeight": "2.1",
                "load": "1.5",
                "emptyWeight": "0.6",
                "sm": "4",
                "crew": "5",
                "passengers": "0",
                "dr": "1",
                "range": "FP",
                "cost": "5000",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "3",
                "name": "Faering, 20'",
                "code": "faering",
                "hp": "32",
                "st": "0",
                "hnd": "1",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1.25",
                "skill": "Boating/TL3 (Unpowered)",
                "loadedWeight": "1.25",
                "load": "1",
                "emptyWeight": "0.25",
                "sm": "3",
                "crew": "6",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "2500",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Jolly Boat, 18'",
                "code": "jollyBoat",
                "hp": "36",
                "st": "0",
                "hnd": "0",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1",
                "skill": "Boating/TL4 (Unpowered)",
                "loadedWeight": "1.35",
                "load": "1",
                "emptyWeight": "0.35",
                "sm": "3",
                "crew": "6",
                "passengers": "2",
                "dr": "2",
                "range": "FP",
                "cost": "3000",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Longboat, 30'",
                "code": "longboat",
                "hp": "43",
                "st": "0",
                "hnd": "1",
                "sr": "1",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "3",
                "moveDownwind": "3",
                "acceleration": "1.25",
                "skill": "Boating/TL4 (Unpowered)",
                "loadedWeight": "1.75",
                "load": "1.15",
                "emptyWeight": "0.6",
                "sm": "5",
                "crew": "9",
                "passengers": "2",
                "dr": "2",
                "range": "FP",
                "cost": "5000",
                "locations": "O",
                "draft": "1",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "4",
                "name": "Voyageur Canoe, 35'",
                "code": "voyageurCanoe",
                "hp": "33",
                "st": "0",
                "hnd": "1",
                "sr": "2",
                "ht": "14",
                "htCodes": "c",
                "moveRoad": "0",
                "moveGood": "0",
                "moveAverage": "0",
                "moveUpwind": "4",
                "moveDownwind": "4",
                "acceleration": "1.25",
                "skill": "Boating/TL4 (Unpowered)",
                "loadedWeight": "5.75",
                "load": "5.5",
                "emptyWeight": "0.25",
                "sm": "5",
                "crew": "15",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "1900",
                "locations": "O",
                "draft": "2",
                "air": false,
                "naval": true,
                "ground": false
            },
            {
                "tl": "0",
                "name": "Dogsled",
                "code": "dogsled",
                "hp": "27",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "moveRoad": "6",
                "moveGood": "6",
                "moveAverage": "3",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "6",
                "skill": "Teamster",
                "loadedWeight": "0.29",
                "load": "0.14",
                "emptyWeight": "0.15",
                "sm": "1",
                "crew": "1",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "400",
                "locations": "14DER",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "1",
                "name": "Fifty-Man Sledge",
                "code": "fiftyManSledge",
                "hp": "77",
                "st": "0",
                "hnd": "-4",
                "sr": "5",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "2",
                "moveGood": "2",
                "moveAverage": "1",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "2",
                "skill": "Teamster",
                "loadedWeight": "4",
                "load": "0.5",
                "emptyWeight": "3.5",
                "sm": "2",
                "crew": "0",
                "passengers": "0",
                "dr": "12",
                "range": "FP",
                "cost": "2500",
                "locations": "50DR",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "1",
                "name": "Heavy Chariot",
                "code": "heavyChariot",
                "hp": "23",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "7",
                "moveGood": "3",
                "moveAverage": "1.5",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "3",
                "skill": "Teamster",
                "loadedWeight": "0.39",
                "load": "0.3",
                "emptyWeight": "0.09",
                "sm": "2",
                "crew": "1",
                "passengers": "2",
                "dr": "2",
                "range": "FP",
                "cost": "660",
                "locations": "4DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "1",
                "name": "Light Chariot",
                "code": "lightChariot",
                "hp": "16",
                "st": "0",
                "hnd": "1",
                "sr": "1",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "9",
                "moveGood": "4",
                "moveAverage": "2",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "0.23",
                "load": "0.2",
                "emptyWeight": "0.03",
                "sm": "1",
                "crew": "1",
                "passengers": "1",
                "dr": "1",
                "range": "FP",
                "cost": "330",
                "locations": "2DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "1",
                "name": "Oxcart",
                "code": "oxcart",
                "hp": "34",
                "st": "0",
                "hnd": "-3",
                "sr": "3",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "1",
                "moveGood": "1",
                "moveAverage": "0.5",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "1",
                "skill": "Teamster",
                "loadedWeight": "0.9",
                "load": "0.6",
                "emptyWeight": "0.3",
                "sm": "1",
                "crew": "0",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "340",
                "locations": "2D2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "1",
                "name": "Straddle Car",
                "code": "straddleCar",
                "hp": "14",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "5",
                "moveGood": "5",
                "moveAverage": "2.5",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "2",
                "skill": "Teamster",
                "loadedWeight": "0.12",
                "load": "0.1",
                "emptyWeight": "0.02",
                "sm": "1",
                "crew": "1",
                "passengers": "0",
                "dr": "0",
                "range": "FP",
                "cost": "165",
                "locations": "1DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "2",
                "name": "Battle Car",
                "code": "battleCar",
                "hp": "14",
                "st": "0",
                "hnd": "2",
                "sr": "1",
                "ht": "11",
                "htCodes": "c",
                "moveRoad": "10",
                "moveGood": "4",
                "moveAverage": "2",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "0.22",
                "load": "0.2",
                "emptyWeight": "0.02",
                "sm": "1",
                "crew": "1",
                "passengers": "1",
                "dr": "1",
                "range": "FP",
                "cost": "250",
                "locations": "2DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "3",
                "name": "Wagon",
                "code": "wagon",
                "hp": "35",
                "st": "0",
                "hnd": "-3",
                "sr": "4",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "8",
                "moveGood": "4",
                "moveAverage": "2",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "0.84",
                "load": "0.5",
                "emptyWeight": "0.34",
                "sm": "2",
                "crew": "1",
                "passengers": "0",
                "dr": "2",
                "range": "FP",
                "cost": "680",
                "locations": "2DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "3",
                "name": "War Wagon",
                "code": "warWagon",
                "hp": "50",
                "st": "0",
                "hnd": "-4",
                "sr": "5",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "6",
                "moveGood": "3",
                "moveAverage": "1.5",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "3",
                "skill": "Teamster",
                "loadedWeight": "3",
                "load": "2",
                "emptyWeight": "1",
                "sm": "4",
                "crew": "2",
                "passengers": "18",
                "dr": "5",
                "range": "FP",
                "cost": "2000",
                "locations": "4DE2W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "4",
                "name": "Carriage",
                "code": "carriage",
                "hp": "47",
                "st": "0",
                "hnd": "-1",
                "sr": "2",
                "ht": "10",
                "htCodes": "c",
                "moveRoad": "10",
                "moveGood": "4",
                "moveAverage": "2",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "1.6",
                "load": "0.8",
                "emptyWeight": "0.8",
                "sm": "2",
                "crew": "1",
                "passengers": "6",
                "dr": "2",
                "range": "FP",
                "cost": "7500",
                "locations": "2DO4W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "4",
                "name": "Coach",
                "code": "coach",
                "hp": "54",
                "st": "0",
                "hnd": "-2",
                "sr": "3",
                "ht": "12",
                "htCodes": "c",
                "moveRoad": "9",
                "moveGood": "4",
                "moveAverage": "2",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "2.4",
                "load": "1.2",
                "emptyWeight": "1.2",
                "sm": "3",
                "crew": "1",
                "passengers": "9",
                "dr": "2",
                "range": "FP",
                "cost": "11000",
                "locations": "4DO4W",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            },
            {
                "tl": "4",
                "name": "Sleigh",
                "code": "sleigh",
                "hp": "23",
                "st": "0",
                "hnd": "0",
                "sr": "2",
                "ht": "10",
                "htCodes": "c",
                "moveRoad": "6",
                "moveGood": "6",
                "moveAverage": "3",
                "moveUpwind": "0",
                "moveDownwind": "0",
                "acceleration": "4",
                "skill": "Teamster",
                "loadedWeight": "0.3",
                "load": "0.2",
                "emptyWeight": "0.1",
                "sm": "1",
                "crew": "1",
                "passengers": "1",
                "dr": "1",
                "range": "FP",
                "cost": "2000",
                "locations": "1DOR",
                "draft": "0",
                "air": false,
                "naval": false,
                "ground": true
            }
        ]

        return vehicles;
    }

    static showVehicleCatalogue(type, tl) {
        let vehicles = this.fetchVehicles();
        let buttons = {};
        let htmlContent = "<div>"
        htmlContent += "<table class='vehicle-catalogue-table'>"

        if (type.toLowerCase() === "naval") {
            htmlContent += "<tr>" +
                "<td style='text-align: center;'>TL</td>" +
                "<td style='text-align: center;'>Vehicle</td>" +
                "<td style='text-align: center;'>ST/HP</td>" +
                "<td style='text-align: center;'>Hnd/SR</td>" +
                "<td style='text-align: center;'>HT</td>" +
                "<td style='text-align: center;'>Acceleration (mph)</td>" +
                "<td style='text-align: center;'>Upwind Move (mph)</td>" +
                "<td style='text-align: center;'>Downwind Move (mph)</td>" +
                "<td style='text-align: center;'>Empty Weight (lbs)</td>" +
                "<td style='text-align: center;'>Full Load (lbs)</td>" +
                "<td style='text-align: center;'>Loaded Weight (lbs)</td>" +
                "<td style='text-align: center;'>SM</td>" +
                "<td style='text-align: center;'>Crew</td>" +
                "<td style='text-align: center;'>Passengers</td>" +
                "<td style='text-align: center;'>Potential Steerage</td>" +
                "<td style='text-align: center;'>DR</td>" +
                "<td style='text-align: center;'>Range</td>" +
                "<td style='text-align: center;'>Cost</td>" +
                "<td style='text-align: center;'>Locations</td>" +
                "<td style='text-align: center;'>Draft</td>" +
                "</tr>"

            vehicles.forEach( vehicle => {
                if (vehicle.naval && tl >= vehicle.tl) {

                    htmlContent += "<tr>" +
                        "<td style='text-align: right;'>" + vehicle.tl + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.name + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.st + "/" + vehicle.hp + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.hnd + "/" + vehicle.sr + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.ht + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.acceleration * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveUpwind * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveDownwind * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.emptyWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.load * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.loadedWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.sm + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.crew + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.passengers + "</td>" +
                        "<td style='text-align: right;'>" + Math.floor(parseInt(vehicle.load)) + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.dr + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.range < 0 ? "∞" : vehicle.range) + "</td>" +
                        "<td style='text-align: right;'>" + parseInt(vehicle.cost).toLocaleString('en') + "$</td>" +
                        "<td style='text-align: center;'>" + vehicle.locations + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.draft + "</td>" +
                        "</tr>"
                }
            })
        }
        else if (type.toLowerCase() === "ground") {
            htmlContent += "<tr>" +
                "<td style='text-align: center;'>TL</td>" +
                "<td style='text-align: center;'>Vehicle</td>" +
                "<td style='text-align: center;'>ST/HP</td>" +
                "<td style='text-align: center;'>Hnd/SR</td>" +
                "<td style='text-align: center;'>HT</td>" +
                "<td style='text-align: center;'>Acceleration (mph)</td>" +
                "<td style='text-align: center;'>Average Terrain Move (mph)</td>" +
                "<td style='text-align: center;'>Good Terrain Move (mph)</td>" +
                "<td style='text-align: center;'>Road Move (mph)</td>" +
                "<td style='text-align: center;'>Empty Weight (lbs)</td>" +
                "<td style='text-align: center;'>Full Load (lbs)</td>" +
                "<td style='text-align: center;'>Loaded Weight (lbs)</td>" +
                "<td style='text-align: center;'>SM</td>" +
                "<td style='text-align: center;'>Crew</td>" +
                "<td style='text-align: center;'>Passengers</td>" +
                "<td style='text-align: center;'>Potential Steerage</td>" +
                "<td style='text-align: center;'>DR</td>" +
                "<td style='text-align: center;'>Range</td>" +
                "<td style='text-align: center;'>Cost</td>" +
                "<td style='text-align: center;'>Locations</td>" +
                "</tr>"

            vehicles.forEach( vehicle => {
                if (vehicle.ground && tl >= vehicle.tl) {
                    htmlContent += "<tr>" +
                        "<td style='text-align: right;'>" + vehicle.tl + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.name + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.st + "/" + vehicle.hp + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.hnd + "/" + vehicle.sr + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.ht + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.acceleration * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveAverage * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveGood * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveRoad * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.emptyWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.load * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.loadedWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.sm + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.crew + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.passengers + "</td>" +
                        "<td style='text-align: right;'>" + Math.floor(parseInt(vehicle.load)) + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.dr + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.range < 0 ? "∞" : vehicle.range) + "</td>" +
                        "<td style='text-align: right;'>" + parseInt(vehicle.cost).toLocaleString('en') + "$</td>" +
                        "<td style='text-align: center;'>" + vehicle.locations + "</td>" +
                        "</tr>"
                }
            })
        }
        else if (type.toLowerCase() === "air") {
            htmlContent += "<tr>" +
                "<td style='text-align: center;'>TL</td>" +
                "<td style='text-align: center;'>Vehicle</td>" +
                "<td style='text-align: center;'>ST/HP</td>" +
                "<td style='text-align: center;'>Hnd/SR</td>" +
                "<td style='text-align: center;'>HT</td>" +
                "<td style='text-align: center;'>Acceleration (mph)</td>" +
                "<td style='text-align: center;'>Move (mph)</td>" +
                "<td style='text-align: center;'>Empty Weight (lbs)</td>" +
                "<td style='text-align: center;'>Full Load (lbs)</td>" +
                "<td style='text-align: center;'>Loaded Weight (lbs)</td>" +
                "<td style='text-align: center;'>SM</td>" +
                "<td style='text-align: center;'>Crew</td>" +
                "<td style='text-align: center;'>Passengers</td>" +
                "<td style='text-align: center;'>Potential Steerage</td>" +
                "<td style='text-align: center;'>DR</td>" +
                "<td style='text-align: center;'>Range</td>" +
                "<td style='text-align: center;'>Cost</td>" +
                "<td style='text-align: center;'>Locations</td>" +
                "</tr>"

            vehicles.forEach( vehicle => {
                if (vehicle.air && tl >= vehicle.tl) {
                    htmlContent += "<tr>" +
                        "<td style='text-align: right;'>" + vehicle.tl + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.name + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.st + "/" + vehicle.hp + "</td>" +
                        "<td style='text-align: center;'>" + vehicle.hnd + "/" + vehicle.sr + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.ht + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.acceleration * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.moveGood * 2) + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.emptyWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.load * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.loadedWeight * 2000).toLocaleString('en') + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.sm + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.crew + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.passengers + "</td>" +
                        "<td style='text-align: right;'>" + Math.floor(parseInt(vehicle.load)) + "</td>" +
                        "<td style='text-align: right;'>" + vehicle.dr + "</td>" +
                        "<td style='text-align: right;'>" + (vehicle.range < 0 ? "∞" : vehicle.range) + "</td>" +
                        "<td style='text-align: right;'>" + parseInt(vehicle.cost).toLocaleString('en') + "$</td>" +
                        "<td style='text-align: center;'>" + vehicle.locations + "</td>" +
                        "</tr>"
                }
            })
        }

        htmlContent += "</table>"
        htmlContent += "</div>"

        buttons.cancel = {
            icon: '<i class="fas fa-times"></i>',
            label: "Close",
            callback: () => {}
        }

        let catalogueDialog =  new Dialog({
            title: "Vehicle Catalogue",
            content: htmlContent,
            buttons: buttons,
            default: "cancel",
            render: html => console.info("Register interactivity in the rendered dialog"),
            close: html => console.info("This always is logged no matter which option is chosen")
        },{
            resizable: true,
            width: "1300",
            height: "750"
        })

        catalogueDialog.render(true);
    }
}
